if(NOT DEFINED HOST_CMAKE)
  message(FATAL_ERROR "HOST_CMAKE must be provided")
endif()
if(NOT DEFINED NIRNLAB_SOURCE_DIR)
  message(FATAL_ERROR "NIRNLAB_SOURCE_DIR must be provided")
endif()
if(NOT DEFINED NIRNLAB_BINARY_DIR)
  message(FATAL_ERROR "NIRNLAB_BINARY_DIR must be provided")
endif()
if(NOT DEFINED NIRNLAB_OUTPUT_PATH)
  message(FATAL_ERROR "NIRNLAB_OUTPUT_PATH must be provided")
endif()
if(NOT DEFINED NIRNLAB_VCPKG_ROOT)
  message(FATAL_ERROR "NIRNLAB_VCPKG_ROOT must be provided")
endif()
if(NOT DEFINED NIRNLAB_GENERATOR)
  message(FATAL_ERROR "NIRNLAB_GENERATOR must be provided")
endif()

if(DEFINED NIRNLAB_CMAKE_DIR AND NOT NIRNLAB_CMAKE_DIR STREQUAL "")
  set(ENV{PATH} "${NIRNLAB_CMAKE_DIR};$ENV{PATH}")
endif()
set(ENV{VCPKG_ROOT} "${NIRNLAB_VCPKG_ROOT}")

set(_cmd
  "${HOST_CMAKE}"
  -S "${NIRNLAB_SOURCE_DIR}"
  -B "${NIRNLAB_BINARY_DIR}"
  -G "${NIRNLAB_GENERATOR}"
)
if(DEFINED NIRNLAB_GENERATOR_PLATFORM AND NOT NIRNLAB_GENERATOR_PLATFORM STREQUAL "")
  list(APPEND _cmd -A "${NIRNLAB_GENERATOR_PLATFORM}")
endif()
if(DEFINED NIRNLAB_GENERATOR_TOOLSET AND NOT NIRNLAB_GENERATOR_TOOLSET STREQUAL "")
  list(APPEND _cmd -T "${NIRNLAB_GENERATOR_TOOLSET}")
endif()
list(APPEND _cmd "-DOUTPUT_PATH:PATH=${NIRNLAB_OUTPUT_PATH}")

execute_process(
  COMMAND ${_cmd}
  RESULT_VARIABLE _result
  COMMAND_ECHO STDOUT
)

if(NOT _result EQUAL 0)
  message(FATAL_ERROR "Failed to configure NirnLab external build (exit code ${_result})")
endif()
