[Debug]

; 0 - trace, 1 - debug, 2 - info, 3 - warn, 4 - error, 5 - critical, 6 - none
LogLevel = 0

; If enabled, it will run the cmd with the game console data
Cmd = true

; Set left offset for cmd
CmdOffsetLeft = 0

; Set top offset for cmd
CmdOffsetTop = 720

; Set width for cmd
CmdWidth = 1900

; Set height for cmd
CmdHeight = 317

; Set Cmd stay on top of others windows
CmdIsAlwaysOnTop = false

; Enables Chromium functionality
ChromiumEnabled = true


[Main]

; List of plugin folders to load plugins from
PluginFolders = Data/Platform/Plugins;Data/Platform/PluginsDev

[Browser]

BackendName = nirnlab
